import type { CharacterDef } from '../engine/types';

export const CHARACTERS: Record<string, CharacterDef> = {
  tidecaller: {
    id: 'tidecaller',
    name: 'The Tidecaller',
    title: 'Priestess of the Drowned Moon',
    icon: 'GiTrident',
    color: 'var(--color-glow)',
    maxHp: 72,
    starterRelic: 'livingCoral',
    starterDeck: [
      { card: 'tideStrike', count: 4 },
      { card: 'kelpGuard', count: 4 },
      { card: 'riptide', count: 1 },
      { card: 'undertow', count: 1 },
    ],
    blurb: 'Reads the tide and strikes when it rises. Toxin, spines, and the patience of the moon.',
    mechanic: 'Tide — time Flood cards for High tide, Ebb cards for Low, or Shift the cycle yourself.',
  },
  voltaic: {
    id: 'voltaic',
    name: 'The Voltaic',
    title: 'Eel-Blooded Duelist',
    icon: 'GiElectric',
    color: 'var(--color-volt)',
    maxHp: 70,
    starterRelic: 'stormCore',
    starterDeck: [
      { card: 'joltStrike', count: 4 },
      { card: 'eelGuard', count: 4 },
      { card: 'staticField', count: 1 },
      { card: 'arcLash', count: 1 },
    ],
    blurb: 'Banks voltage with every move, then spends the whole storm at once.',
    mechanic: 'Charge — Conduct cards bank it, Discharge cards consume it all for massive effects.',
    lockText: 'Defeat the Act I boss to recruit the eel-blooded.',
  },
  drowned: {
    id: 'drowned',
    name: 'The Drowned',
    title: 'What the Sea Gave Back',
    icon: 'GiDrowning',
    color: 'var(--color-drowned)',
    maxHp: 80,
    starterRelic: 'barnacledHeart',
    starterDeck: [
      { card: 'drownedGrip', count: 4 },
      { card: 'soddenGuard', count: 4 },
      { card: 'openVein', count: 1 },
      { card: 'sunkenFury', count: 1 },
    ],
    blurb: 'Came back from the deep wrong. Pays in blood — and the sea pays it back with interest.',
    mechanic: 'Descent — HP lost on your turn becomes Descent. Cards grow with it; Surface cards cash it in.',
    lockText: 'Defeat two act bosses in one dive. The sea returns what it takes.',
  },
  weaver: {
    id: 'weaver',
    name: 'The Wakeweaver',
    title: 'Never Once Bitten',
    icon: 'GiFishEscape',
    color: 'var(--color-weaver)',
    maxHp: 68,
    starterRelic: 'weaversInstinct',
    starterDeck: [
      { card: 'needleJab', count: 4 },
      { card: 'slipAside', count: 4 },
      { card: 'readTheWater', count: 1 },
      { card: 'undertowFeint', count: 1 },
    ],
    blurb: 'Reads the wakes things leave in the water — and is simply never where the teeth arrive.',
    mechanic: 'Read — cards that trigger off enemy telegraphs. Foresight shows every intent one move further ahead.',
    lockText: 'End three battles untouched in a single dive. Nothing has ever touched her.',
  },
};
